version: 0.1

phases:
  build:
    commands:
      - dotnet restore src/LambdaFunction.sln
      - dotnet publish src/LambdaFunction.sln
      - zip lambda.zip src/LambdaFunction/bin/Release/netcoreapp1.1/publish/*
