version: 0.2

phases:
  build:
    commands:
      - dotnet restore src/LambdaFunction.sln
      - dotnet publish src/LambdaFunction.sln -c Release
      - zip lambda.zip src/LambdaFunction/bin/Release/netcoreapp1.1/publish/*
      - aws lambda update-function-code --function-name NumbersGame --zip-file fileb://lambda.zip
