version: 0.2

phases:
  build:
    commands:
      - dotnet restore src/LambdaFunction.sln
      - dotnet publish src/LambdaFunction.sln -c Release
      - cd src/LambdaFunction/bin/Release/netcoreapp1.1/publish
      - zip ../../../../../../lambda.zip *
      - cd ../../../../../..
      - /root/bin/aws lambda update-function-code --function-name NumbersGame --zip-file fileb://lambda.zip
