version: 0.2

phases:
  install:
    commands:
      - apt-get update      
      - apt-get -y install zip
      - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
      - unzip awscli-bundle.zip
      - ./awscli-bundle/install -b ~/bin/aws
  build:
    commands:
      - dotnet restore src/LambdaFunction.sln
      - dotnet publish src/LambdaFunction.sln -c Release
      - zip lambda.zip src/LambdaFunction/bin/Release/netcoreapp1.1/publish/*
      - /root/bin/aws lambda update-function-code --function-name NumbersGame --zip-file fileb://lambda.zip
